spring.application.name=veiculoService

spring.datasource.url=jdbc:postgresql://localhost:5432/veiculo_db
spring.datasource.username=postgres
spring.datasource.password=adm

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



